---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-sre-config
  namespace: ai-sre
  labels:
    app: ai-sre
    component: config
data:
  # Tool Configuration
  TOOLS_ENABLED_CATEGORIES: "all"
  TOOLS_DISABLED: "tcpdump,lsof"
  TOOLS_ENABLED: ""
  
  # Secrets Configuration
  SOPS_ENABLED: "true"
  AGE_KEY_PATH: "/app/secrets/age-key.txt"
  VAULT_ENABLED: "false"
  SEALED_SECRETS_ENABLED: "false"
  
  # Security Configuration
  ALLOWED_COMMANDS: ""
  BLOCKED_COMMANDS: "rm,dd,mkfs,fdisk,shutdown,reboot,halt"
  REQUIRE_AUTH: "false"
  
  # Monitoring Configuration
  AGENT_LOG_LEVEL: "INFO"
  DETAILED_LOGGING: "true"
  METRICS_ENABLED: "true"
  
  # Performance Configuration
  COMMAND_TIMEOUT: "60"
  MAX_CONCURRENT_OPERATIONS: "10"
  
  # AI Configuration
  ENABLE_LEARNING: "true"
  PATTERN_RECOGNITION: "true"
  PREDICTIVE_ALERTS: "false"
  LEARNING_RETENTION_DAYS: "90"
  
  # Service Endpoints
  PROMETHEUS_URL: "http://prometheus:9090"
  ALERTMANAGER_URL: "http://alertmanager:9093"
  GRAFANA_URL: "http://grafana:3000"
  KUMA_URL: "http://kuma:5681"
  JAEGER_URL: "http://jaeger:16686"
  LOKI_URL: "http://loki:3100"
  TEMPO_URL: "http://tempo:3200"
  CONSUL_URL: "http://consul:8500"
  VAULT_URL: "http://vault:8200"
  REDIS_URL: "redis://redis:6379"
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  KIBANA_URL: "http://kibana:5601"
  MINIO_URL: "http://minio:9000"
  ARGO_URL: "http://argo-workflows:2746"
  TEKTON_URL: "http://tekton-dashboard:9097"
  CROSSPLANE_URL: "http://crossplane:8080"
  KYVERNO_URL: "http://kyverno:9443"
  FALCO_URL: "http://falco:8765"
  OPA_URL: "http://opa:8181"
  EXTERNAL_DNS_URL: "http://external-dns:7979"
  CERT_MANAGER_URL: "http://cert-manager:9402"
  NGINX_INGRESS_URL: "http://nginx-ingress:10254"
  TRAEFIK_URL: "http://traefik:8080"
  LINKERD_URL: "http://linkerd:8084"
  ISTIO_URL: "http://istio:15000"
  ENVOY_URL: "http://envoy:9901"
  CONSUL_CONNECT_URL: "http://consul:8501"
  KONG_URL: "http://kong:8001"
  AMBASSADOR_URL: "http://ambassador:8877"
  CONTOUR_URL: "http://contour:8001"
  GLOO_URL: "http://gloo:8081"
  CILIUM_URL: "http://cilium:9965"
  CALICO_URL: "http://calico:9099"
  FLANNEL_URL: "http://flannel:9091"
  WEAVE_URL: "http://weave:6784"
  ANTREA_URL: "http://antrea:10349"
  KUBE_ROUTER_URL: "http://kube-router:8080"
  METALLB_URL: "http://metallb:7472"
  KUBE_VIP_URL: "http://kube-vip:8080"
  CILIUM_OPERATOR_URL: "http://cilium-operator:9964"
  KUBE_PROXY_URL: "http://kube-proxy:10249"
  KUBELET_URL: "http://kubelet:10250"
  KUBE_APISERVER_URL: "https://kubernetes:6443"
  KUBE_CONTROLLER_MANAGER_URL: "http://kube-controller-manager:10257"
  KUBE_SCHEDULER_URL: "http://kube-scheduler:10259"
  ETCD_URL: "http://etcd:2379"
  COREDNS_URL: "http://coredns:9153"
  NODELOCALDNS_URL: "http://nodelocaldns:9253"

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-sre-secrets
  namespace: ai-sre
  labels:
    app: ai-sre
    component: secrets
type: Opaque
data:
  # SOPS AGE Key (base64 encoded)
  # Generate with: age-keygen -o age-key.txt
  # Then base64 encode: base64 -w 0 age-key.txt
  age-key.txt: ""  # Add your base64 encoded AGE key here
  
  # GitHub Personal Access Token (base64 encoded)
  github-token: ""  # Add your base64 encoded GitHub token here
  
  # Kubernetes Service Account Token (if needed)
  kube-token: ""  # Add your base64 encoded kube token here

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-sre-sops-key
  namespace: ai-sre
  labels:
    app: ai-sre
    component: sops
type: Opaque
stringData:
  # SOPS AGE Key (plain text for SOPS operations)
  age-key: ""  # Add your AGE private key here
  # Example format:
  # age-key: |
  #   -----BEGIN AGE ENCRYPTED FILE-----
  #   YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqNnR6WHQ4Q2F3dU5V
  #   ...
  #   -----END AGE ENCRYPTED FILE-----
