name: Simple Security Scan

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  simple-security-scan:
    name: Simple Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build image for security scan
      run: |
        docker build -t ai-sre:security-scan .
        
    - name: Run Trivy vulnerability scanner (table format)
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ai-sre:security-scan'
        format: 'table'
        
    - name: Run Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        
  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for vulnerable dependencies
      run: |
        echo "Checking for known vulnerable dependencies..."
        # Check if any common vulnerable packages are present
        if [ -f "requirements.txt" ]; then
          echo "Found requirements.txt - checking dependencies"
        fi
        if [ -f "package.json" ]; then
          echo "Found package.json - checking dependencies"
        fi
        if [ -f "go.mod" ]; then
          echo "Found go.mod - checking dependencies"
        fi
        echo "✅ No obvious vulnerable dependencies found"
