name: Simple Test

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  simple-test:
    name: Simple Container Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" =~ ^refs/tags/v ]]; then
          echo "Release build - building for multiple platforms"
          docker buildx build --platform linux/amd64,linux/arm64 -t ai-sre:simple-test .
        else
          echo "Non-release build - building for AMD64 only"
          docker buildx build --platform linux/amd64 -t ai-sre:simple-test .
        fi
        
    - name: Test container startup
      run: |
        docker run -d --name ai-sre-simple-test -p 8080:8080 ai-sre:simple-test
        sleep 15
        
    - name: Test basic endpoints
      run: |
        # Test basic health endpoints
        curl -f http://localhost:8080/health || exit 1
        curl -f http://localhost:8080/ready || exit 1
        curl -f http://localhost:8080/version || exit 1
        
        echo "✅ Basic endpoints working"
        
    - name: Test CLI tools in container
      run: |
        # Test that CLI tools are available
        docker exec ai-sre-simple-test kubectl version --client
        docker exec ai-sre-simple-test helm version --client
        docker exec ai-sre-simple-test flux version --client
        docker exec ai-sre-simple-test git --version
        
        echo "✅ CLI tools available"
        
    - name: Cleanup
      if: always()
      run: |
        docker stop ai-sre-simple-test || true
        docker rm ai-sre-simple-test || true
