name: Multi-Platform Testing

on:
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  test-matrix:
    name: Test on ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        exclude:
          - os: macos-latest
            arch: arm64  # GitHub doesn't support ARM64 macOS runners yet
            
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        docker build --platform linux/${{ matrix.arch }} -t ai-sre:test-${{ matrix.arch }} .
        
    - name: Test container startup
      run: |
        docker run -d --name ai-sre-test-${{ matrix.arch }} -p 8080:8080 ai-sre:test-${{ matrix.arch }}
        sleep 10
        
    - name: Test MCP Server endpoints
      run: |
        curl -f http://localhost:8080/health || exit 1
        curl -f http://localhost:8080/ready || exit 1
        curl -f http://localhost:8080/version || exit 1
        
    - name: Test kubectl functionality
      run: |
        curl -f -X POST http://localhost:8080/kubectl/version \
          -H "Content-Type: application/json" \
          -d '{}' || exit 1
          
    - name: Test git functionality
      run: |
        curl -f -X POST http://localhost:8080/git/status \
          -H "Content-Type: application/json" \
          -d '{}' || exit 1
          
    - name: Test flux functionality
      run: |
        curl -f -X POST http://localhost:8080/flux/version \
          -H "Content-Type: application/json" \
          -d '{}' || exit 1
          
    - name: Verify CLI tools
      run: |
        docker exec ai-sre-test-${{ matrix.arch }} kubectl version --client
        docker exec ai-sre-test-${{ matrix.arch }} helm version --client
        docker exec ai-sre-test-${{ matrix.arch }} flux version --client
        docker exec ai-sre-test-${{ matrix.arch }} git --version
        
    - name: Check container stats
      run: |
        docker stats --no-stream ai-sre-test-${{ matrix.arch }}
        
    - name: Cleanup
      if: always()
      run: |
        docker stop ai-sre-test-${{ matrix.arch }} || true
        docker rm ai-sre-test-${{ matrix.arch }} || true
